waypoints:
  - {x: 6.0, y: 0.0, yaw: 1.57}
  - {x: 6.0, y: 6.0, yaw: 3.14}
  - {x: -6.0, y: 6.0, yaw: -1.57}
  - {x: -6.0, y: -6.0, yaw: 0.0}
  - {x: 0.0, y: -6.0, yaw: 1.57}
  - {x: 0.0, y: 6.0, yaw: 0.0}
  - {x: 6.0, y: 6.0, yaw: -1.57}
  - {x: 6.0, y: -6.0, yaw: 3.14}
  - {x: 0.0, y: -6.0, yaw: 1.57}
  - {x: 0.0, y: 6.0, yaw: 3.14}
  - {x: -6.0, y: 6.0, yaw: -1.57}
  - {x: -6.0, y: 0.0, yaw: 0.0}
  - {x: 0.0, y: 0.0, yaw: 0.0}

